package com.cabsystem.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * User Entity - Demonstrates ENCAPSULATION
 * All fields are private and accessed through getters/setters (auto-generated by Lombok)
 */
@Entity
@Table(name = "users")
@Data  // Lombok: Generates getters, setters, toString, equals, hashCode
@NoArgsConstructor  // Lombok: Generates no-args constructor
@AllArgsConstructor  // Lombok: Generates all-args constructor
public class User {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long userId;
    
    @Column(nullable = false)
    private String name;
    
    @Column(nullable = false, unique = true)
    private String email;
    
    @Column(nullable = false)
    private String phone;
    
    @Column(nullable = false)
    private String address;
    
    @Column(nullable = false)
    private String password;  // Hashed password (SHA-256)
    
    @Column(nullable = false)
    private String role = "USER";  // USER or ADMIN
    
    /**
     * Business method - Encapsulated within the User class
     */
    public String getMaskedPhone() {
        if (phone != null && phone.length() >= 4) {
            return "******" + phone.substring(phone.length() - 4);
        }
        return "****";
    }
    
    /**
     * Validation method
     */
    public boolean isValidEmail() {
        return email != null && email.contains("@");
    }
}
